/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeeZFile */

#ifndef _Included_DeeZFile
#define _Included_DeeZFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DeeZFile
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DeeZFile_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     DeeZFile
 * Method:    setLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_DeeZFile_setLogLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     DeeZFile
 * Method:    getFileCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DeeZFile_getFileCount
  (JNIEnv *, jobject);

/*
 * Class:     DeeZFile
 * Method:    getComment
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DeeZFile_getComment
  (JNIEnv *, jobject, jint);

/*
 * Class:     DeeZFile
 * Method:    getRecords
 * Signature: (Ljava/lang/String;I)[LDeeZFile/SAMRecord;
 */
JNIEXPORT jobjectArray JNICALL Java_DeeZFile_getRecords
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     DeeZFile
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DeeZFile_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
